### ISSUE TITLE
Multiples tabs at once not possible

### ISSUE THREAD

**Issue by chrinx** [DeathMiner/RewardsGG-Farm#10]
Hi, thx for this tool it really nice. But pls find a way you can have opened more tabs at the same time to get more tickets. would be nice. ^^

**Comment by demaisj** [comment]
Hello,

You have to use proxies & multiple accounts, otherwise it won't work, and there is no workaround.
Indeed thanks for your support!

**Comment by demaisj** [comment]
Multi-tab is now useless and will be blocked in the next version.
