### ISSUE TITLE
The Tickets And Total Earned Tickets Are Glitched

### ISSUE THREAD

**Issue by MinersMC** [DeathMiner/RewardsGG-Farm#13]
The Tickets when earned will glitch like 30002020
and the Total Earned Tickets Like 02020
Please fix ?

**Comment by demaisj** [comment]
Hello,

I already know this bug, I Will fix it as soon as I can.
Indeed thanks for your support!

**Comment by MinersMC** [comment]
@DeathMiner Thank you!

**Comment by demaisj** [comment]
This bug is fixed in Version 2.1.
