### ISSUE TITLE
 Getting some extra tickets in some minutes! (ads)

### ISSUE THREAD

**Issue by kiki286** [DeathMiner/RewardsGG-Farm#14]
It isn't giving the tickets or the time till getting tickets. Already tried closing and opening. On the adds bar it just shows Getting some extra tickets in some minutes! (ads)

**Comment by demaisj** [comment]
Hello,

can you give me a screenshot of the console & network tabs of the Chrome DevTools while you load the farm ?
And also a screen of add-adv-click-tickets headers & response tabs in the network section.

Thanks for your support.

**Comment by kiki286** [comment]
It fixed itself after a while! 👍  Great farm

**Comment by demaisj** [comment]
Ok no worries if it displays a "some" it means that the script didn't loaded the most accurate number of tickets or wait time.
Indeed thanks for your support.
