### ISSUE TITLE
Doesn't seem to work.

### ISSUE THREAD

**Issue by hysasuke** [DeathMiner/RewardsGG-Farm#15]
I install the extension, and the script for Rewards.gg, and then I logged in and click on GET TICKETS, however, the stream is still showing and the page is not showing like the screenshot on your instruction page, and I am pretty sure that the extension is on . I don't know if I did something wrong, it just seems like doesn't work. Please help, thanks a lot!

**Comment by demaisj** [comment]
Hello,

I don't know what could be your problem, so we'll check if you completed all the steps of installation:
1. Go the the Chrome Web Store & install the Tampermonkey extension
2. Go on Github & click on Install, installing the latest version (v2.2.2)
3. Go on rewards.gg, login with your account
4. Go on the Get Tickets page.

It is working for me, the rewards.gg team did no update for their website, so the script can't be broken.

Tell me if you have more details about your problem.
Thanks for your support anyway!

**Comment by hysasuke** [comment]
I did follow all the steps, and I did install the latest version which is v2.2.2, I also tried with Tampermonkey beta version, but it doesn't work too. And when I get on to the Get Tickets page, on the top right of my google chrome, there is a white 1 with red background shows, I'm pretty sure that it means that the script is running, so I still don't know what is wrong.

**Comment by demaisj** [comment]
Can you open the DevTools (F12) & show me a screenshot of the Console tab?

**Comment by hysasuke** [comment]
![1](https://cloud.githubusercontent.com/assets/19693290/15720134/11eb039e-2801-11e6-807f-1ab8414f16e4.JPG)

**Comment by hysasuke** [comment]
![1](https://cloud.githubusercontent.com/assets/19693290/15720192/4bbffc6e-2801-11e6-8a06-a21276d4f5a7.JPG)

**Comment by demaisj** [comment]
Okay, please delete the script in the Tampermonkey Dashboard & reinstall the script, without typing something in the code below on the installation page.

**Comment by hysasuke** [comment]
I did that, but still the same with syntax error. I promise you that I didn't edit anything about the script.

**Comment by demaisj** [comment]
Is your chrome browser up to date?

**Comment by hysasuke** [comment]
Yes, it it, i will update it and then try. Thanks for your help!

**Comment by hysasuke** [comment]
Oh it works! Thank a lot !!!!!!!

**Comment by demaisj** [comment]
Nice man!
So another problem I won't have to deal with :+1:

Thanks for your support mate!

**Comment by hysasuke** [comment]
I am studying computer science in university, hope someday i will be as awesome as you, lol.
