### ISSUE TITLE
Stream is now playing

### ISSUE THREAD

**Issue by LePoissonBleu** [DeathMiner/RewardsGG-Farm#24]
I dont know how they pulled that one out.
But right now the stream is playing in the farm because I can hear it!
Wasnt like that 10 min ago lol.

**Comment by demaisj** [comment]
Hi,

Have you tried refreshing the page a couple times ? Does the farm still open its black & green interface ?
If an update is needed, I'm still waiting for the _HUGE 2.0 UPDATE_ as they claim. If they change some things regarding ticket farming it might be worth it to wait & not work for nothing.

Thanks for the support.

**Comment by LePoissonBleu** [comment]
Reopening browser seemed to be the fix. Refresh did not work. Btw, I consider it a possible 'wifi loss', reconnecting issue. This is when it happened. It's working just fine now!

**Comment by demaisj** [comment]
Ok nice!

You can reopen this issue if you encounter this bug one more time.
