### ISSUE TITLE
Cannot use more than one account at the same time

### ISSUE THREAD

**Issue by StormKiller1** [DeathMiner/RewardsGG-Farm#3]
the bot says login to farm tickets after i logged in with many accounts but before it whas working it started i think yesterday

**Comment by demaisj** [comment]
Hello,

Are you using multiple browser sessions? Eg. A simple chrome tab & a incognito chrome tab

And if they are blocking multiples account on the same IP, have you tried using a different proxy for each account?

**Comment by StormKiller1** [comment]
yes im using multilogin with chrome but how can i have a proxy for every account/tab?

**Comment by demaisj** [comment]
I think you must have a different IP for each account, otherwise you will be banned. But I don't know efficient proxy solutions for this problem.

**Comment by demaisj** [comment]
This script can work on only one account per session. Use different environments to farm tickets from multiple accounts.
