### ISSUE TITLE
v1.5-beta update issues

### ISSUE THREAD

**Issue by poorloading** [DeathMiner/RewardsGG-Farm#6]
it is farming tickets but the countdown sometimes goes off track and the TICKETS FARMED counter is not keeping track at all as in it never moves from 0. not complaining just figured if you was told it would help you out and help you get it down with less work =]

**Comment by poorloading** [comment]
Also, for some reason I get signed out randomly I don't know why

**Comment by demaisj** [comment]
Hello,

The "Tickets Farmed" counter is not yet implemented. I didn't changed the behavior of the script regarding the ticket farming, i've just changed the design so it is usable (plus some adblock compatibility).
Also I don't know why you get signed out, i'll check myself if I got that problem too.

Thanks for beta testing the farm, i'll tell you when the dev branch will recieve updates.

**Comment by poorloading** [comment]
ill keep testing  and posting any bugs or issues i find

**Comment by poorloading** [comment]
ill post more about the sign out issue when it happens again

**Comment by demaisj** [comment]
If you want, you can also give me the console log & network log when it happens, so I have more information to analyse it.

**Comment by poorloading** [comment]
sure just tell me how

**Comment by demaisj** [comment]
1. Hit the F12 Key on the Farm page, it will open the dev tools
2. Go the the console tab, and take a screenshot of it (when it happens)
3. Go to the network tab, take a screenshot of it too
4. On the network tab, click on the latest addTickets request, and screenshot the Headers & Response tabs

This should be enough data to do some debugging.

**Comment by poorloading** [comment]
that issue stopped for me but a new one has been happening, even tho the  farmer is running and ui is up all the audio for the video is playing and hearable

**Comment by poorloading** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8119364/14065710/981e9dc8-f402-11e5-9b11-25fe332bf72b.png)
![untitled2](https://cloud.githubusercontent.com/assets/8119364/14065711/981f8508-f402-11e5-8e4e-5c90405edb49.png)
![untitled3](https://cloud.githubusercontent.com/assets/8119364/14065709/981e5c0a-f402-11e5-91b6-7a6999479f48.png)

**Comment by demaisj** [comment]
Hi, I've also noticed that bug.
The small Star & Issue buttons, when loaded from the first time, glitches and show the get tickets page inside them. To solve the issue just press F5, and it should stop.

**Comment by demaisj** [comment]
Hi, I'm rolling out 1.5 update, this issue will be closed too.
