### ISSUE TITLE
Can't see the timing and I'm not getting any tickets plus i see all the ads

### ISSUE THREAD

**Issue by Crazyyfaith** [DeathMiner/RewardsGG-Farm#7]
Just installed the script and don't see the timer, i waited to see if i was getting any but no so the script completely doesn't work

**Comment by poorloading** [comment]
it's been outdated for a little awhile but the guy is working on it. there is a beta version posted in on the other issue posts.

**Comment by Crazyyfaith** [comment]
@poorloading My Name is Boxxy <3

**Comment by poorloading** [comment]
i love Boxxy xD

**Comment by poorloading** [comment]
@Crazyyfaith  i love Boxxy

**Comment by demaisj** [comment]
Hello,

As poorloading said, the script is currently out of date, but i'm working on a new version, that you can download in beta state here : https://github.com/DeathMiner/RewardsGG-Farm/blob/dev/rewardsgg-farm.user.js
This weekend I'll have some time to finish the new update, and to roll it out for every users.

Sorry for making you wait.

**Comment by demaisj** [comment]
Closing it, since its a duplicate of #4
