### ISSUE TITLE
Farm stats server not working

### ISSUE THREAD

**Issue by demaisj** [DeathMiner/RewardsGG-Farm#8]
The server hosting the farm stats is not working at all.
If you have any free or (very) cheap hosting solution, fell free to say it here!
(moved from issue #1)

**Comment by poorloading** [comment]
you mean something like this ? http://5jelly.info/vps/

**Comment by demaisj** [comment]
I'll take a peek into this one.
But stats servers seems to work for now, also I noticed it was stuck on an endless loop!
We'll see in the future how the situation will evolve.

**Comment by demaisj** [comment]
Yay! I found a server, the farm stats are coming back in the following days.

**Comment by demaisj** [comment]
Stats are now working since version 2.2

**Comment by demaisj** [comment]
Stats are now working since version 2.2
